name: HazeCrates
version: ${version}
main: it.haze.hazecrates.HazeCrates
api-version: '1.21'
softdepend: [PlaceholderAPI, Vault, MMOItems, ItemsAdder, Nexo]
permissions:
  hazecrates.admin:    { default: op }
  hazecrates.key:      { default: op, description: 'Puo dare e togliere chiavi' }
  hazecrates.item:     { default: op, description: 'Puo ricevere l item di piazzamento' }
  hazecrates.preview:  { default: true }
  hazecrates.open.*:   { default: true }
