name: NyxonCrates
version: ${version}
main: net.nyxon.crates.NyxonCrates
api-version: '1.21'
softdepend: [PlaceholderAPI, Vault, MMOItems, ItemsAdder, Nexo]
permissions:
  nyxoncrates.admin:    { default: op }
  nyxoncrates.key:      { default: op, description: 'Puo dare e togliere chiavi' }
  nyxoncrates.item:     { default: op, description: 'Puo ricevere l item di piazzamento' }
  nyxoncrates.preview:  { default: true }
  nyxoncrates.open.*:   { default: true }
